
RPEngineProfilesDB = {
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "Ortellus",
},
["_schema"] = 1,
["profiles"] = {
["Test NPC"] = {
["stats"] = {
["NATURE"] = {
["visible"] = 1,
["id"] = "NATURE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "nature",
["default"] = 0,
},
["name"] = "Nature",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["id"] = "MAX_HEALTH",
["pct"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["itemTooltipPriority"] = 0,
},
["REACTION"] = {
["visible"] = 0,
["id"] = "REACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
["itemTooltipPriority"] = 0,
},
["SPI"] = {
["visible"] = 1,
["id"] = "SPI",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 13,
["name"] = "Spirit",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Spirit",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["itemTooltipPriority"] = 100,
},
["ATHLETICS"] = {
["visible"] = 1,
["id"] = "ATHLETICS",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "athletics",
["default"] = 0,
},
["name"] = "Athletics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["INTIMIDATION"] = {
["visible"] = 1,
["id"] = "INTIMIDATION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "intimidation",
["default"] = 0,
},
["name"] = "Intimidation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MAX_MANA"] = {
["visible"] = 0,
["id"] = "MAX_MANA",
["pct"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["PERFORMANCE"] = {
["visible"] = 1,
["id"] = "PERFORMANCE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "performance",
["default"] = 0,
},
["name"] = "Performance",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["STEALTH"] = {
["visible"] = 1,
["id"] = "STEALTH",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "stealth",
["default"] = 0,
},
["name"] = "Stealth",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["HOLY_RESIST"] = {
["visible"] = 1,
["id"] = "HOLY_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Holy",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["CHA"] = {
["visible"] = 1,
["id"] = "CHA",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 11,
["name"] = "Charisma",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Charisma",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["itemTooltipPriority"] = 100,
},
["MELEE_AP"] = {
["visible"] = 1,
["id"] = "MELEE_AP",
["max"] = {
["ruleKey"] = "max_melee_ap",
},
["base"] = {
["ruleKey"] = "melee_ap",
["default"] = 0,
},
["pct"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$ Melee Attack Power",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["SLEIGHT_OF_HAND"] = {
["visible"] = 1,
["id"] = "SLEIGHT_OF_HAND",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "sleight_of_hand",
["default"] = 0,
},
["name"] = "Sleight of Hand",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["PERSUASION"] = {
["visible"] = 1,
["id"] = "PERSUASION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "persuasion",
["default"] = 0,
},
["name"] = "Persuasion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["BLOCK"] = {
["visible"] = 1,
["id"] = "BLOCK",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Block Chance",
["name"] = "Block Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["itemTooltipPriority"] = 99,
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["id"] = "MAX_HOLY_POWER",
["pct"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = 3,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["SPELL_CRIT"] = {
["visible"] = 1,
["id"] = "SPELL_CRIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "spell_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["NATURE_RESIST"] = {
["visible"] = 1,
["id"] = "NATURE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Nature",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["SHADOW_RESIST"] = {
["visible"] = 1,
["id"] = "SHADOW_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Shadow",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["DODGE"] = {
["visible"] = 1,
["id"] = "DODGE",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Dodge Chance",
["name"] = "Dodge Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["itemTooltipPriority"] = 99,
},
["MELEE_HIT"] = {
["visible"] = 1,
["id"] = "MELEE_HIT",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Melee Hit Chance",
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["ARCANA"] = {
["visible"] = 1,
["id"] = "ARCANA",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "arcana",
["default"] = 0,
},
["name"] = "Arcana",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["PERCEPTION"] = {
["visible"] = 1,
["id"] = "PERCEPTION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "perception",
["default"] = 0,
},
["name"] = "Perception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["RANGED_AP"] = {
["visible"] = 1,
["id"] = "RANGED_AP",
["min"] = 0,
["pct"] = 0,
["name"] = "Ranged Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "ranged_ap",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["INT"] = {
["visible"] = 1,
["id"] = "INT",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 15,
["name"] = "Intellect",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Intellect",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["itemTooltipPriority"] = 100,
},
["ARCANE_RESIST"] = {
["visible"] = 1,
["id"] = "ARCANE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Arcane",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["id"] = "BONUS_ACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
["itemTooltipPriority"] = 0,
},
["SURVIVAL"] = {
["visible"] = 1,
["id"] = "SURVIVAL",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "survival",
["default"] = 0,
},
["name"] = "Survival",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["FIRE_RESIST"] = {
["visible"] = 1,
["id"] = "FIRE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Fire",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["DECEPTION"] = {
["visible"] = 1,
["id"] = "DECEPTION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "deception",
["default"] = 0,
},
["name"] = "Deception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MELEE_CRIT"] = {
["visible"] = 1,
["id"] = "MELEE_CRIT",
["pct"] = 1,
["base"] = {
["ruleKey"] = "melee_crit",
["default"] = 0,
},
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Melee Crit. Chance",
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["STA"] = {
["visible"] = 1,
["id"] = "STA",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 14,
["name"] = "Stamina",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Stamina",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["itemTooltipPriority"] = 100,
},
["RANGED_CRIT"] = {
["visible"] = 1,
["id"] = "RANGED_CRIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "ranged_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["FROST_RESIST"] = {
["visible"] = 1,
["id"] = "FROST_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Frost",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["STR"] = {
["visible"] = 1,
["id"] = "STR",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 12,
["name"] = "Strength",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Strength",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["itemTooltipPriority"] = 100,
},
["MANA"] = {
["visible"] = 1,
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.\n\nYour maximum mana is $stat.MAX_MANA$.",
["max"] = {
["ref"] = "MAX_MANA",
},
["min"] = 0,
["base"] = 75,
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\n\nYour maximum health is $stat.MAX_HEALTH$.",
["max"] = {
["ref"] = "MAX_HEALTH",
},
["min"] = 0,
["base"] = 0,
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["itemTooltipPriority"] = 0,
},
["HISTORY"] = {
["visible"] = 1,
["id"] = "HISTORY",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "history",
["default"] = 0,
},
["name"] = "History",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MEDICINE"] = {
["visible"] = 1,
["id"] = "MEDICINE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "medicine",
["default"] = 0,
},
["name"] = "Medicine",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["HOLY_POWER"] = {
["visible"] = 1,
["id"] = "HOLY_POWER",
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["min"] = 0,
["base"] = 0,
["name"] = "Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["SPELL_HIT"] = {
["visible"] = 1,
["id"] = "SPELL_HIT",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Spell Hit Chance",
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 99,
},
["ANIMAL_HANDLING"] = {
["visible"] = 1,
["id"] = "ANIMAL_HANDLING",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "animal_handling",
["default"] = 0,
},
["name"] = "Animal Handling",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["INVESTIGATION"] = {
["visible"] = 1,
["id"] = "INVESTIGATION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "investigation",
["default"] = 0,
},
["name"] = "Investigation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["INSIGHT"] = {
["visible"] = 1,
["id"] = "INSIGHT",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "insight",
["default"] = 0,
},
["name"] = "Insight",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["PARRY"] = {
["visible"] = 1,
["id"] = "PARRY",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Parry Chance",
["name"] = "Parry Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["itemTooltipPriority"] = 99,
},
["SPELL_AP"] = {
["visible"] = 1,
["id"] = "SPELL_AP",
["min"] = 0,
["pct"] = 0,
["name"] = "Spell Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "spell_power",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["RANGED_HIT"] = {
["visible"] = 1,
["id"] = "RANGED_HIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["AGI"] = {
["visible"] = 1,
["id"] = "AGI",
["itemLevelWeight"] = 230,
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 10,
["name"] = "Agility",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Agility",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["itemTooltipPriority"] = 100,
},
["ACTION"] = {
["visible"] = 0,
["id"] = "ACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["itemTooltipPriority"] = 0,
},
["RELIGION"] = {
["visible"] = 1,
["id"] = "RELIGION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "religion",
["default"] = 0,
},
["name"] = "Religion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["ACROBATICS"] = {
["visible"] = 1,
["id"] = "ACROBATICS",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "acrobatics",
["default"] = 0,
},
["name"] = "Acrobatics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
},
["spells"] = {
["spell-e71626a8"] = 1,
},
["actionBar"] = {
{
["spellId"] = "spell-e71626a8",
["rank"] = 1,
},
},
["items"] = {
},
["createdAt"] = 1761511164,
["name"] = "Test NPC",
["professions"] = {
["cooking"] = {
["id"] = "Cooking",
["level"] = 0,
["spec"] = "",
["recipes"] = {
},
},
["profession1"] = {
["id"] = "",
["level"] = 0,
["spec"] = "",
["recipes"] = {
},
},
["fishing"] = {
["id"] = "Fishing",
["level"] = 0,
["spec"] = "",
["recipes"] = {
},
},
["profession2"] = {
["id"] = "",
["level"] = 0,
["spec"] = "",
["recipes"] = {
},
},
["firstaid"] = {
["id"] = "First Aid",
["level"] = 0,
["spec"] = "",
["recipes"] = {
},
},
},
["paletteName"] = "Default",
["equipment"] = {
},
["updatedAt"] = 1761770392,
},
["Ortellus-Argent Dawn"] = {
["stats"] = {
["HOLY_POWER"] = {
["visible"] = 1,
["id"] = "HOLY_POWER",
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["min"] = 0,
["name"] = "Holy Power",
["category"] = "RESOURCE",
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["pct"] = 0,
},
["MELEE_CRIT"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["id"] = "MELEE_CRIT",
},
["STA"] = {
["visible"] = 1,
["name"] = "Stamina",
["category"] = "PRIMARY",
["id"] = "STA",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["base"] = 14,
["pct"] = 0,
},
["STR"] = {
["visible"] = 1,
["name"] = "Strength",
["category"] = "PRIMARY",
["id"] = "STR",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["base"] = 12,
["pct"] = 0,
},
["SPI"] = {
["visible"] = 1,
["name"] = "Spirit",
["category"] = "PRIMARY",
["id"] = "SPI",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["base"] = 13,
["pct"] = 0,
},
["INT"] = {
["visible"] = 1,
["name"] = "Intellect",
["category"] = "PRIMARY",
["id"] = "INT",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["base"] = 15,
["pct"] = 0,
},
["FIRE_RESIST"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Fire",
["category"] = "RESISTANCE",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["id"] = "FIRE_RESIST",
},
["MAX_MANA"] = {
["visible"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["id"] = "MAX_MANA",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 100,
["pct"] = 0,
},
["MANA"] = {
["visible"] = 1,
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.",
["min"] = 0,
["name"] = "Mana",
["category"] = "RESOURCE",
["max"] = {
["ref"] = "MAX_MANA",
},
["base"] = 75,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["pct"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.",
["min"] = 0,
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["max"] = {
["ref"] = "MAX_HEALTH",
},
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["pct"] = 0,
},
["CHA"] = {
["visible"] = 1,
["name"] = "Charisma",
["category"] = "PRIMARY",
["id"] = "CHA",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["base"] = 11,
["pct"] = 0,
},
["MELEE_AP"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Attack Power",
["category"] = "SECONDARY",
["pct"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["id"] = "MELEE_AP",
},
["FROST_RESIST"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Frost",
["category"] = "RESISTANCE",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["id"] = "FROST_RESIST",
},
["ARCANE_RESIST"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Arcane",
["category"] = "RESISTANCE",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["id"] = "ARCANE_RESIST",
},
["NATURE_RESIST"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Nature",
["category"] = "RESISTANCE",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["id"] = "NATURE_RESIST",
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["id"] = "MAX_HOLY_POWER",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 3,
["pct"] = 0,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["id"] = "MAX_HEALTH",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = 100,
["pct"] = 0,
},
["MELEE_HIT"] = {
["visible"] = 1,
["min"] = 0,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["id"] = "MELEE_HIT",
},
["AGI"] = {
["visible"] = 1,
["name"] = "Agility",
["category"] = "PRIMARY",
["id"] = "AGI",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["base"] = 10,
["pct"] = 0,
},
},
["updatedAt"] = 1757034774,
["name"] = "Ortellus-Argent Dawn",
["createdAt"] = 1757034736,
},
["peyne-argentdawn"] = {
["items"] = {
{
["id"] = "cursed_ring",
["qty"] = 1,
},
{
["id"] = "longsword",
["qty"] = 1,
},
},
["stats"] = {
["NATURE"] = {
["visible"] = 1,
["id"] = "NATURE",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Nature",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "nature",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["MAX_HEALTH"] = {
["visible"] = 0,
["id"] = "MAX_HEALTH",
["itemTooltipPriority"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["pct"] = 0,
},
["REACTION"] = {
["visible"] = 0,
["id"] = "REACTION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["SPI"] = {
["visible"] = 1,
["id"] = "SPI",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["name"] = "Spirit",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Spirit",
["base"] = 13,
["pct"] = 0,
},
["ATHLETICS"] = {
["visible"] = 1,
["id"] = "ATHLETICS",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Athletics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "athletics",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["INTIMIDATION"] = {
["visible"] = 1,
["id"] = "INTIMIDATION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Intimidation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "intimidation",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["MAX_MANA"] = {
["visible"] = 0,
["id"] = "MAX_MANA",
["itemTooltipPriority"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 0,
},
["pct"] = 0,
},
["PERFORMANCE"] = {
["visible"] = 1,
["id"] = "PERFORMANCE",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Performance",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "performance",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["STEALTH"] = {
["visible"] = 1,
["id"] = "STEALTH",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Stealth",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "stealth",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["HOLY_RESIST"] = {
["visible"] = 1,
["id"] = "HOLY_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Holy",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["CHA"] = {
["visible"] = 1,
["id"] = "CHA",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["name"] = "Charisma",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Charisma",
["base"] = 11,
["pct"] = 0,
},
["MELEE_AP"] = {
["visible"] = 1,
["id"] = "MELEE_AP",
["itemTooltipPriority"] = 99,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipColor"] = {
0,
1,
0,
},
["min"] = 0,
["itemTooltipFormat"] = "$value$ Melee Attack Power",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = {
["ruleKey"] = "melee_ap",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_melee_ap",
},
},
["SLEIGHT_OF_HAND"] = {
["visible"] = 1,
["id"] = "SLEIGHT_OF_HAND",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Sleight of Hand",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "sleight_of_hand",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["SHADOW_RESIST"] = {
["visible"] = 1,
["id"] = "SHADOW_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Shadow",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["id"] = "MAX_HOLY_POWER",
["itemTooltipPriority"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 3,
["pct"] = 0,
},
["SPELL_CRIT"] = {
["visible"] = 1,
["id"] = "SPELL_CRIT",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = {
["ruleKey"] = "spell_crit",
["default"] = 0,
},
["pct"] = 1,
},
["NATURE_RESIST"] = {
["visible"] = 1,
["id"] = "NATURE_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Nature",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["HOLY_POWER"] = {
["visible"] = 1,
["id"] = "HOLY_POWER",
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["base"] = 0,
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
},
["INT"] = {
["visible"] = 1,
["id"] = "INT",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["name"] = "Intellect",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Intellect",
["base"] = 15,
["pct"] = 0,
},
["PERCEPTION"] = {
["visible"] = 1,
["id"] = "PERCEPTION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Perception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "perception",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["RANGED_AP"] = {
["visible"] = 1,
["id"] = "RANGED_AP",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Ranged Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = {
["ruleKey"] = "ranged_ap",
["default"] = 0,
},
["pct"] = 0,
},
["MELEE_HIT"] = {
["visible"] = 1,
["id"] = "MELEE_HIT",
["itemTooltipPriority"] = 99,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipColor"] = {
0,
1,
0,
},
["min"] = 0,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$% Melee Hit Chance",
["base"] = 0,
["pct"] = 1,
},
["ARCANE_RESIST"] = {
["visible"] = 1,
["id"] = "ARCANE_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Arcane",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["id"] = "BONUS_ACTION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["SURVIVAL"] = {
["visible"] = 1,
["id"] = "SURVIVAL",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Survival",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "survival",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["FIRE_RESIST"] = {
["visible"] = 1,
["id"] = "FIRE_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Fire",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["DECEPTION"] = {
["visible"] = 1,
["id"] = "DECEPTION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Deception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "deception",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["SPELL_HIT"] = {
["visible"] = 1,
["id"] = "SPELL_HIT",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["ACTION"] = {
["visible"] = 0,
["id"] = "ACTION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["RANGED_CRIT"] = {
["visible"] = 1,
["id"] = "RANGED_CRIT",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = {
["ruleKey"] = "ranged_crit",
["default"] = 0,
},
["pct"] = 1,
},
["MELEE_CRIT"] = {
["visible"] = 1,
["id"] = "MELEE_CRIT",
["itemTooltipPriority"] = 99,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipColor"] = {
0,
1,
0,
},
["min"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$% Melee Crit. Chance",
["base"] = {
["ruleKey"] = "melee_crit",
["default"] = 0,
},
["pct"] = 1,
},
["INSIGHT"] = {
["visible"] = 1,
["id"] = "INSIGHT",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Insight",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "insight",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["MANA"] = {
["visible"] = 1,
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.\n\nYour maximum mana is $stat.MAX_MANA$.",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["pct"] = 0,
["base"] = 75,
["max"] = {
["ref"] = "MAX_MANA",
},
},
["HEALTH"] = {
["visible"] = 1,
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\n\nYour maximum health is $stat.MAX_HEALTH$.",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["pct"] = 0,
["base"] = 0,
["max"] = {
["ref"] = "MAX_HEALTH",
},
},
["STA"] = {
["visible"] = 1,
["id"] = "STA",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["name"] = "Stamina",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Stamina",
["base"] = 14,
["pct"] = 0,
},
["MEDICINE"] = {
["visible"] = 1,
["id"] = "MEDICINE",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Medicine",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "medicine",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["STR"] = {
["visible"] = 1,
["id"] = "STR",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["name"] = "Strength",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Strength",
["base"] = 12,
["pct"] = 0,
},
["ARCANA"] = {
["visible"] = 1,
["id"] = "ARCANA",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Arcana",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "arcana",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["ANIMAL_HANDLING"] = {
["visible"] = 1,
["id"] = "ANIMAL_HANDLING",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Animal Handling",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "animal_handling",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["INVESTIGATION"] = {
["visible"] = 1,
["id"] = "INVESTIGATION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Investigation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "investigation",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["HISTORY"] = {
["visible"] = 1,
["id"] = "HISTORY",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "History",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "history",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["FROST_RESIST"] = {
["visible"] = 1,
["id"] = "FROST_RESIST",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Frost",
["category"] = "RESISTANCE",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 1,
},
["SPELL_AP"] = {
["visible"] = 1,
["id"] = "SPELL_AP",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Spell Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = {
["ruleKey"] = "spell_power",
["default"] = 0,
},
["pct"] = 0,
},
["RANGED_HIT"] = {
["visible"] = 1,
["id"] = "RANGED_HIT",
["min"] = 0,
["itemTooltipPriority"] = 0,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = 0,
["pct"] = 1,
},
["AGI"] = {
["visible"] = 1,
["id"] = "AGI",
["itemTooltipPriority"] = 100,
["itemTooltipColor"] = {
1,
1,
1,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["name"] = "Agility",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Agility",
["base"] = 10,
["pct"] = 0,
},
["PERSUASION"] = {
["visible"] = 1,
["id"] = "PERSUASION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Persuasion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "persuasion",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["RELIGION"] = {
["visible"] = 1,
["id"] = "RELIGION",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Religion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "religion",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["ACROBATICS"] = {
["visible"] = 1,
["id"] = "ACROBATICS",
["itemTooltipPriority"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Acrobatics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["base"] = {
["ruleKey"] = "acrobatics",
["default"] = 0,
},
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
},
["name"] = "peyne-argentdawn",
["updatedAt"] = 1757718493,
["createdAt"] = 1757718002,
["equipment"] = {
},
},
["Ortellus"] = {
["stats"] = {
["STAT-e25dfa56"] = {
["visible"] = 1,
["itemTooltipPriority"] = 0,
["id"] = "STAT-e25dfa56",
["itemLevelWeight"] = 0,
["min"] = nil --[[ inf ]],
["name"] = "Test Stat",
["category"] = "PRIMARY",
["recovery"] = "",
["pct"] = 0,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
},
["spells"] = {
},
["actionBar"] = {
},
["items"] = {
},
["createdAt"] = 1764296898,
["name"] = "Ortellus",
["paletteName"] = "Default",
["professions"] = {
["cooking"] = {
["id"] = "Cooking",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["profession1"] = {
["id"] = "",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["fishing"] = {
["id"] = "Fishing",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["profession2"] = {
["id"] = "",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["firstaid"] = {
["id"] = "First Aid",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
},
["updatedAt"] = 1764300286,
["equipment"] = {
},
},
["NPC 3"] = {
["items"] = {
{
["id"] = "cursed_ring",
["qty"] = 1,
},
{
["id"] = "longsword",
["qty"] = 1,
},
},
["stats"] = {
["NATURE"] = {
["visible"] = 1,
["id"] = "NATURE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "nature",
["default"] = 0,
},
["name"] = "Nature",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["id"] = "MAX_HEALTH",
["pct"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["itemTooltipPriority"] = 0,
},
["REACTION"] = {
["visible"] = 0,
["id"] = "REACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
["itemTooltipPriority"] = 0,
},
["SPI"] = {
["visible"] = 1,
["id"] = "SPI",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 13,
["name"] = "Spirit",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Spirit",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["itemTooltipPriority"] = 100,
},
["ATHLETICS"] = {
["visible"] = 1,
["id"] = "ATHLETICS",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "athletics",
["default"] = 0,
},
["name"] = "Athletics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["INTIMIDATION"] = {
["visible"] = 1,
["id"] = "INTIMIDATION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "intimidation",
["default"] = 0,
},
["name"] = "Intimidation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MAX_MANA"] = {
["visible"] = 0,
["id"] = "MAX_MANA",
["pct"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["PERFORMANCE"] = {
["visible"] = 1,
["id"] = "PERFORMANCE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "performance",
["default"] = 0,
},
["name"] = "Performance",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["STEALTH"] = {
["visible"] = 1,
["id"] = "STEALTH",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "stealth",
["default"] = 0,
},
["name"] = "Stealth",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["HOLY_RESIST"] = {
["visible"] = 1,
["id"] = "HOLY_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Holy",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["CHA"] = {
["visible"] = 1,
["id"] = "CHA",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 11,
["name"] = "Charisma",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Charisma",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["itemTooltipPriority"] = 100,
},
["MELEE_AP"] = {
["visible"] = 1,
["id"] = "MELEE_AP",
["max"] = {
["ruleKey"] = "max_melee_ap",
},
["base"] = {
["ruleKey"] = "melee_ap",
["default"] = 0,
},
["pct"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$ Melee Attack Power",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["SLEIGHT_OF_HAND"] = {
["visible"] = 1,
["id"] = "SLEIGHT_OF_HAND",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "sleight_of_hand",
["default"] = 0,
},
["name"] = "Sleight of Hand",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["SHADOW_RESIST"] = {
["visible"] = 1,
["id"] = "SHADOW_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Shadow",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["id"] = "MAX_HOLY_POWER",
["pct"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["base"] = 3,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["SPELL_CRIT"] = {
["visible"] = 1,
["id"] = "SPELL_CRIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "spell_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["NATURE_RESIST"] = {
["visible"] = 1,
["id"] = "NATURE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Nature",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["HOLY_POWER"] = {
["visible"] = 1,
["id"] = "HOLY_POWER",
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["min"] = 0,
["base"] = 0,
["name"] = "Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["INT"] = {
["visible"] = 1,
["id"] = "INT",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 15,
["name"] = "Intellect",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Intellect",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["itemTooltipPriority"] = 100,
},
["PERCEPTION"] = {
["visible"] = 1,
["id"] = "PERCEPTION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "perception",
["default"] = 0,
},
["name"] = "Perception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["RANGED_AP"] = {
["visible"] = 1,
["id"] = "RANGED_AP",
["min"] = 0,
["pct"] = 0,
["name"] = "Ranged Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "ranged_ap",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["MELEE_HIT"] = {
["visible"] = 1,
["id"] = "MELEE_HIT",
["pct"] = 1,
["base"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Melee Hit Chance",
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["ARCANE_RESIST"] = {
["visible"] = 1,
["id"] = "ARCANE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Arcane",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["id"] = "BONUS_ACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
["itemTooltipPriority"] = 0,
},
["SURVIVAL"] = {
["visible"] = 1,
["id"] = "SURVIVAL",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "survival",
["default"] = 0,
},
["name"] = "Survival",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["FIRE_RESIST"] = {
["visible"] = 1,
["id"] = "FIRE_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Fire",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["DECEPTION"] = {
["visible"] = 1,
["id"] = "DECEPTION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "deception",
["default"] = 0,
},
["name"] = "Deception",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["SPELL_HIT"] = {
["visible"] = 1,
["id"] = "SPELL_HIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["ACTION"] = {
["visible"] = 0,
["id"] = "ACTION",
["max"] = 1,
["min"] = 0,
["base"] = 1,
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["itemTooltipPriority"] = 0,
},
["RANGED_CRIT"] = {
["visible"] = 1,
["id"] = "RANGED_CRIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "ranged_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["MELEE_CRIT"] = {
["visible"] = 1,
["id"] = "MELEE_CRIT",
["pct"] = 1,
["base"] = {
["ruleKey"] = "melee_crit",
["default"] = 0,
},
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Melee Crit. Chance",
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipPriority"] = 99,
},
["INSIGHT"] = {
["visible"] = 1,
["id"] = "INSIGHT",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "insight",
["default"] = 0,
},
["name"] = "Insight",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["MANA"] = {
["visible"] = 1,
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.\n\nYour maximum mana is $stat.MAX_MANA$.",
["max"] = {
["ref"] = "MAX_MANA",
},
["min"] = 0,
["base"] = 75,
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["itemTooltipPriority"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\n\nYour maximum health is $stat.MAX_HEALTH$.",
["max"] = {
["ref"] = "MAX_HEALTH",
},
["min"] = 0,
["base"] = 0,
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["pct"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["itemTooltipPriority"] = 0,
},
["STA"] = {
["visible"] = 1,
["id"] = "STA",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 14,
["name"] = "Stamina",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Stamina",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["itemTooltipPriority"] = 100,
},
["MEDICINE"] = {
["visible"] = 1,
["id"] = "MEDICINE",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "medicine",
["default"] = 0,
},
["name"] = "Medicine",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["STR"] = {
["visible"] = 1,
["id"] = "STR",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 12,
["name"] = "Strength",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Strength",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["itemTooltipPriority"] = 100,
},
["ARCANA"] = {
["visible"] = 1,
["id"] = "ARCANA",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "arcana",
["default"] = 0,
},
["name"] = "Arcana",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["ANIMAL_HANDLING"] = {
["visible"] = 1,
["id"] = "ANIMAL_HANDLING",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "animal_handling",
["default"] = 0,
},
["name"] = "Animal Handling",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["INVESTIGATION"] = {
["visible"] = 1,
["id"] = "INVESTIGATION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "investigation",
["default"] = 0,
},
["name"] = "Investigation",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["HISTORY"] = {
["visible"] = 1,
["id"] = "HISTORY",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "history",
["default"] = 0,
},
["name"] = "History",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["FROST_RESIST"] = {
["visible"] = 1,
["id"] = "FROST_RESIST",
["min"] = 0,
["pct"] = 1,
["name"] = "Frost",
["category"] = "RESISTANCE",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["SPELL_AP"] = {
["visible"] = 1,
["id"] = "SPELL_AP",
["min"] = 0,
["pct"] = 0,
["name"] = "Spell Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = {
["ruleKey"] = "spell_power",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["RANGED_HIT"] = {
["visible"] = 1,
["id"] = "RANGED_HIT",
["min"] = 0,
["pct"] = 1,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["itemTooltipPriority"] = 0,
},
["AGI"] = {
["visible"] = 1,
["id"] = "AGI",
["pct"] = 0,
["itemTooltipColor"] = {
1,
1,
1,
},
["base"] = 10,
["name"] = "Agility",
["category"] = "PRIMARY",
["recovery"] = 0,
["itemTooltipFormat"] = "$value$ Agility",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["itemTooltipPriority"] = 100,
},
["PERSUASION"] = {
["visible"] = 1,
["id"] = "PERSUASION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "persuasion",
["default"] = 0,
},
["name"] = "Persuasion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["RELIGION"] = {
["visible"] = 1,
["id"] = "RELIGION",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "religion",
["default"] = 0,
},
["name"] = "Religion",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
["ACROBATICS"] = {
["visible"] = 1,
["id"] = "ACROBATICS",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
["min"] = 0,
["base"] = {
["ruleKey"] = "acrobatics",
["default"] = 0,
},
["name"] = "Acrobatics",
["category"] = "SKILL",
["recovery"] = 0,
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipPriority"] = 0,
},
},
["name"] = "NPC 3",
["updatedAt"] = 1757722822,
["equipment"] = {
["mainhand"] = "longsword",
["finger"] = "cursed_ring",
},
["createdAt"] = 1757718769,
},
},
}
RPEngineRulesetDB = {
["rulesets"] = {
["Ruleset 230124"] = {
["rules"] = {
["allowResources"] = "HEALTH, MAX_HEALTH, MANA, MAX_MANA, HOLY_POWER, MAX_HOLY_POWER",
},
["createdAt"] = 1757023284,
["name"] = "Ruleset 230124",
["updatedAt"] = 1757032245,
},
["Ruleset 013052"] = {
["updatedAt"] = 1764300286,
["rules"] = {
["arcana"] = "$stat.SPI$/10",
["nature"] = "$stat.SPI$/10",
["melee_crit"] = "0.05*$stat.AGI$+5",
["perception"] = "$stat.INT$/10",
["sleight_of_hand"] = "$stat.AGI$/10",
["performance"] = "$stat.CHA$/10",
["allow_secondary"] = "{ MELEE_AP, RANGED_AP, SPELL_AP, MELEE_HIT, RANGED_HIT, SPELL_HIT, MELEE_CRIT, RANGED_CRIT, SPELL_CRIT, PARRY, DODGE, BLOCK, DEFENCE, AC }",
["hit_system"] = "complex",
["hit_aoe_roll_mode"] = "per_target",
["intimidation"] = "$stat.CHA$/10",
["allow_primary"] = "{ AGI, INT, SPI, STA, CHA, STR }",
["investigation"] = "$stat.INT$/10",
["hit_default_requires"] = "{ DAMAGE, APPLY_AURA_HARMFUL }",
["max_skill"] = "50",
["max_health"] = "10*$stat.STA$",
["equipment_slots_bottom"] = "{ mainhand, offhand, ranged }",
["max_mana"] = "10*$stat.INT$",
["use_spell_ranks_lvl"] = "1",
["persuasion"] = "$stat.CHA$/10",
["use_spell_ranks"] = "1",
["equipment_slots_right"] = "{ hands, waist, legs, feet, finger, trinket, ammo, relic }",
["ranged_ap"] = "2*$stat.AGI$",
["spell_crit"] = "0.05*$stat.INT$+5",
["stealth"] = "$stat.AGI$/10",
["deception"] = "$stat.CHA$/10",
["hit_base_threshold"] = "50",
["spell_power"] = "2*$stat.INT$",
["allow_resource"] = "{ HEALTH, MAX_HEALTH, MANA, MAX_MANA, ACTION, BONUS_ACTION, REACTION }",
["show_item_level"] = "1",
["survival"] = "$stat.SPI$/10",
["acrobatics"] = "$stat.AGI$/10",
["religion"] = "$stat.SPI$/10",
["melee_ap"] = "2*$stat.STR$ + $stat.AGI$",
["ranged_crit"] = "0.05*$stat.AGI$+5",
["athletics"] = "$stat.STR$/10",
["hit_roll"] = "1d100",
["medicine"] = "$stat.SPI$/10",
["always_hit"] = "0",
["mana_regen"] = "$stat.SPI$/4",
["allow_resistance"] = "{ FIRE_RESIST, FROST_RESIST, NATURE_RESIST, ARCANE_RESIST, SHADOW_RESIST, HOLY_RESIST }",
["use_level_system"] = "1",
["history"] = "$stat.INT$/10",
["animal_handling"] = "$stat.SPI$/10",
["equipment_slots_left"] = "{ head, neck, shoulder, back, chest, shirt, tabard, wrists  }",
["npc_stats"] = "{ DODGE, PARRY, BLOCK, FIRE_RESIST, DEFENCE, AC }",
["health_regen"] = "$stat.SPI$/5",
["insight"] = "$stat.SPI$/10",
["max_tick_units"] = "4",
},
["name"] = "Ruleset 013052",
["createdAt"] = 1757032252,
},
},
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "Ruleset 013052",
},
["_schema"] = 1,
}
RPEngineDatasetDB = {
["datasets"] = {
["RPE Official 1"] = {
["guid"] = "RPEOfficial1-1757872257-125144976",
["extra"] = {
["interactions"] = {
["ixn-7df7f24d"] = {
["id"] = "ixn-7df7f24d",
["options"] = {
{
["args"] = {
["maxStock"] = "inf",
["tags"] = "ink",
},
["action"] = "SHOP",
["label"] = "Shop",
},
{
["args"] = {
["flags"] = "warrior",
["type"] = "SPELLS",
["maxLevel"] = "10",
},
["action"] = "TRAIN",
["label"] = "Train",
},
},
["target"] = "Ink Trader",
},
["ixn-5d9a2abb"] = {
["id"] = "ixn-5d9a2abb",
["options"] = {
{
["label"] = "Salvage",
["action"] = "SALVAGE",
["args"] = {
["maps"] = "37",
},
},
{
["label"] = "Raise Dead",
["action"] = "RAISE",
["args"] = {
},
},
},
["target"] = "type:humanoid",
},
},
["recipes"] = {
["REC-67ece6b0"] = {
["optional"] = {
},
["cost"] = {
["item-4aeda360"] = 1,
},
["id"] = "REC-67ece6b0",
["skill"] = 10,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Dense Triangle Mace",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["quality"] = "rare",
["category"] = "Two-Handed Maces",
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
},
["REC-de3bc56a"] = {
["optional"] = {
},
["id"] = "REC-de3bc56a",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Mace",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["quality"] = "rare",
["category"] = "Two-Handed Maces",
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
},
["REC-a5d82073"] = {
["optional"] = {
},
["id"] = "REC-a5d82073",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Shortsword",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
["category"] = "Two-Handed Maces",
["quality"] = "rare",
},
["REC-c8a9ac6a"] = {
["optional"] = {
},
["cost"] = {
["Copper"] = 134,
["item-abd12b3b"] = 1,
},
["id"] = "REC-c8a9ac6a",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Helmet",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
["category"] = "Two-Handed Maces",
["quality"] = "rare",
},
},
["stats"] = {
["STAT-e435cdcd"] = {
["visible"] = "1",
["max"] = "",
["itemTooltipFormat"] = "",
["tooltip"] = "",
["itemLevelWeight"] = 0,
["base"] = 0,
["min"] = "",
["itemTooltipPriority"] = 0,
["name"] = "Test123",
["category"] = "PRIMARY",
["recovery"] = "",
["pct"] = "0",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["id"] = "STAT-e435cdcd",
},
},
},
["author"] = "Ortellus",
["auras"] = {
["aura-c6e847e7"] = {
["conflictPolicy"] = "NONE",
["duration"] = {
["expires"] = "ON_OWNER_TURN_END",
["turns"] = 10,
},
["description"] = "Deals 10 Fire damage on hit.",
["tags"] = {
},
["id"] = "aura-c6e847e7",
["uniqueByCaster"] = false,
["hidden"] = false,
["immunity"] = {
["dispelTypes"] = {
},
["tags"] = {
},
["helpful"] = false,
["ids"] = {
},
["harmful"] = false,
},
["isHelpful"] = true,
["modifiers"] = {
{
["source"] = "CASTER",
["scaleWithStacks"] = "",
["value"] = "",
["mode"] = "ADD",
["stat"] = "",
["snapshot"] = "DYNAMIC",
},
},
["name"] = "Test Aura",
["stackingPolicy"] = "ADD_MAGNITUDE",
["triggers"] = {
{
["event"] = "ON_HIT",
["action"] = {
["key"] = "DAMAGE",
["targets"] = {
["ref"] = "target",
},
["args"] = {
["amount"] = "10",
},
},
},
},
["maxStacks"] = 1,
["icon"] = 132157,
["unpurgable"] = false,
},
["aura-90a703b1"] = {
["description"] = "Deals $[1].amount$ fire damage every turn.",
["uniqueByCaster"] = true,
["dispelType"] = "MAGIC",
["tick"] = {
["period"] = 1,
["actions"] = {
{
["phase"] = "onResolve",
["logic"] = "ALL",
["actions"] = {
{
["hitModifier"] = "",
["hitThreshold"] = {
},
["key"] = "DAMAGE",
["args"] = {
["threat"] = "",
["requiresHit"] = false,
["perRank"] = "",
["school"] = "Fire",
["amount"] = "5",
["targets"] = {
["targeter"] = "TARGET",
["ref"] = "target",
["maxTargets"] = 1,
},
["hitModifier"] = "",
},
},
},
["requirements"] = {
},
},
},
},
["maxStacks"] = 1,
["icon"] = 135818,
["unpurgable"] = false,
["tags"] = {
},
["id"] = "aura-90a703b1",
["hidden"] = false,
["triggers"] = {
{
["event"] = "ON_HIT",
["action"] = {
["targets"] = {
["ref"] = "target",
},
["key"] = "DAMAGE",
["args"] = {
["amount"] = "",
},
},
},
},
["immunity"] = {
["dispelTypes"] = {
},
["tags"] = {
},
["helpful"] = false,
["harmful"] = false,
["ids"] = {
},
},
["name"] = "Ignite",
["modifiers"] = {
{
["source"] = "CASTER",
["mode"] = "ADD",
["value"] = "",
["snapshot"] = "DYNAMIC",
["stat"] = "",
["scaleWithStacks"] = "",
},
},
["isHelpful"] = false,
["stackingPolicy"] = "REFRESH_DURATION",
["duration"] = {
["expires"] = "ON_OWNER_TURN_END",
["turns"] = 3,
},
["conflictPolicy"] = "KEEP_HIGHER",
},
},
["items"] = {
["item-abd12b3b"] = {
["basePriceU"] = 25,
["description"] = "",
["vendorSellable"] = false,
["id"] = "item-abd12b3b",
["data"] = {
},
["tags"] = {
"test",
},
["priceOverrideC"] = 0,
["itemLevel"] = 0,
["name"] = "Iron Bar",
["category"] = "MATERIAL",
["maxStack"] = 1,
["stackable"] = false,
["icon"] = 133232,
["rarity"] = "common",
},
["item-b7deefa6"] = {
["basePriceU"] = 550,
["description"] = "",
["vendorSellable"] = true,
["id"] = "item-b7deefa6",
["data"] = {
["damageSchool"] = "Physical",
["swingCost"] = " ",
["red_sockets"] = "1",
["maxDamage"] = "14",
["minDamage"] = "6",
["weaponType"] = "Mace",
["stat_STR"] = "10",
["stat_STA"] = "10",
["hand"] = "Two-Handed",
["slot"] = "MAINHAND",
},
["priceOverrideC"] = 0,
["rarity"] = "rare",
["itemLevel"] = 29,
["name"] = "Dense Triangle Mace",
["category"] = "EQUIPMENT",
["maxStack"] = 1,
["stackable"] = false,
["icon"] = 133488,
["tags"] = {
"test",
},
},
["item-4aeda360"] = {
["basePriceU"] = 5,
["description"] = "",
["vendorSellable"] = true,
["id"] = "item-4aeda360",
["data"] = {
},
["rarity"] = "common",
["tags"] = {
"ink",
},
["priceOverrideC"] = 0,
["name"] = "Moonglow Ink",
["category"] = "MATERIAL",
["maxStack"] = 20,
["stackable"] = true,
["icon"] = 237082,
["itemLevel"] = 0,
},
},
["createdAt"] = 1757872257,
["name"] = "RPE Official 1",
["npcs"] = {
["NPC-43db7384"] = {
["stats"] = {
["DODGE"] = 1,
["FIRE_RESIST"] = 4,
["BLOCK"] = 3,
["PARRY"] = 2,
["DEFENCE"] = 5,
["AC"] = 5,
},
["cam"] = 0.6000000000000001,
["id"] = "NPC-43db7384",
["spells"] = {
"spell-e71626a8",
"spell-a4236a4d",
},
["hp"] = {
["base"] = 7,
["perPlayer"] = 8,
},
["fileDataId"] = 125264,
["unitType"] = "Demon",
["name"] = "Test NPC",
["z"] = -0.27,
["team"] = 2,
["unitSize"] = "Huge",
["displayId"] = 33,
["rot"] = 0.15,
},
},
["updatedAt"] = 1764298893,
["version"] = 1,
["spells"] = {
["spell-e71626a8"] = {
["maxRanks"] = 5,
["description"] = "Deals $[1].amount$ damage and generates a large amount of threat.",
["unlockLevel"] = 1,
["id"] = "spell-e71626a8",
["icon"] = 132282,
["data"] = {
},
["cast"] = {
["tickIntervalTurns"] = 1,
["type"] = "CAST_TURNS",
["concentration"] = false,
["turns"] = 1,
["moveAllowed"] = false,
},
["costs"] = {
{
["resource"] = "mana",
["amount"] = "1",
["when"] = "onStart",
["refundOnInterrupt"] = false,
["perRank"] = "1",
},
},
["targeter"] = {
["default"] = "PRECAST",
},
["groups"] = {
{
["requirements"] = {
},
["phase"] = "onResolve",
["logic"] = "ALL",
["actions"] = {
{
["args"] = {
["threat"] = "",
["requiresHit"] = true,
["amount"] = "10",
["school"] = "Ice",
["perRank"] = "",
["targets"] = {
["targeter"] = "PRECAST",
["maxTargets"] = 1,
["flags"] = "E",
},
["hitModifier"] = "$stat.MELEE_HIT$",
},
["hitThreshold"] = {
"$stat.PARRY$",
"$stat.DODGE$",
"$stat.BLOCK$",
},
["key"] = "DAMAGE",
["hitModifier"] = "",
},
{
["key"] = "APPLY_AURA",
["args"] = {
["perRank"] = 0,
["targets"] = {
["targeter"] = "TARGET",
["maxTargets"] = 1,
["flags"] = "E",
},
["auraId"] = "aura-90a703b1",
},
},
},
},
},
["name"] = "Heroic Strike",
["rankInterval"] = 6,
["npcOnly"] = false,
["cooldown"] = {
["turns"] = 2,
["starts"] = "onResolve",
["sharedGroup"] = "test",
},
["tags"] = {
"Warrior",
"Arms",
},
},
["spell-a4236a4d"] = {
["tags"] = {
"fury",
},
["description"] = "Causes your attacks to deal 10 damage on hit.",
["unlockLevel"] = 1,
["id"] = "spell-a4236a4d",
["cooldown"] = {
["turns"] = 1,
["starts"] = "onResolve",
["sharedGroup"] = "test",
},
["maxRanks"] = 1,
["npcOnly"] = false,
["cast"] = {
["tickIntervalTurns"] = 1,
["type"] = "INSTANT",
["concentration"] = false,
["turns"] = 0,
["moveAllowed"] = false,
},
["rankInterval"] = 1,
["groups"] = {
{
["requirements"] = {
},
["actions"] = {
{
["key"] = "APPLY_AURA",
["args"] = {
["perRank"] = 0,
["targets"] = {
["targeter"] = "PRECAST",
["maxTargets"] = 1,
["flags"] = "A",
},
["auraId"] = "aura-c6e847e7",
},
},
},
["logic"] = "ALL",
["phase"] = "onResolve",
},
},
["name"] = "Flaming Strikes",
["targeter"] = {
["default"] = "CASTER",
},
["costs"] = {
{
["resource"] = "mana",
["amount"] = "1",
["when"] = "onStart",
["perRank"] = "1",
["refundOnInterrupt"] = false,
},
},
["icon"] = 132157,
["data"] = {
},
},
},
},
["DefaultDataset"] = {
["guid"] = "DefaultDataset-1757863340-2144619041",
["extra"] = {
["interactions"] = {
},
["stats"] = {
["TEST"] = {
["visible"] = "1",
["max"] = "5",
["itemTooltipFormat"] = "",
["tooltip"] = "",
["itemLevelWeight"] = 0,
["icon"] = "",
["min"] = "0",
["pct"] = "0",
["name"] = "Test Stat",
["category"] = "PRIMARY",
["recovery"] = "",
["itemTooltipPriority"] = 0,
["base"] = 0,
["id"] = "TEST",
},
},
},
["spells"] = {
},
["auras"] = {
},
["items"] = {
},
["createdAt"] = 1757863340,
["name"] = "DefaultDataset",
["npcs"] = {
},
["updatedAt"] = 1764300286,
["version"] = 1,
},
["5e"] = {
["guid"] = "5e-1764293249-1057112397",
["extra"] = {
["interactions"] = {
},
["stats"] = {
["AC"] = {
["itemTooltipPriority"] = 99,
["id"] = "AC",
["min"] = 0,
["name"] = "Armor Class",
["category"] = "SECONDARY",
["itemTooltipFormat"] = "$value$ AC",
["base"] = 10,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["itemTooltipColor"] = {
0,
1,
0,
},
},
["MELEE_CRIT"] = {
["itemTooltipPriority"] = 99,
["id"] = "MELEE_CRIT",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["base"] = {
["ruleKey"] = "melee_crit",
["default"] = 0,
},
["itemTooltipFormat"] = "$value$% Melee Crit. Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["pct"] = 1,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["id"] = "MAX_HEALTH",
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
},
["REACTION"] = {
["visible"] = 0,
["id"] = "REACTION",
["min"] = 0,
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["max"] = 1,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
},
["DEFENCE"] = {
["itemTooltipPriority"] = 99,
["id"] = "DEFENCE",
["min"] = 0,
["name"] = "Defence",
["category"] = "SECONDARY",
["itemTooltipFormat"] = "$value$ Defence",
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["itemTooltipColor"] = {
0,
1,
0,
},
},
["SPI"] = {
["visible"] = 1,
["id"] = "SPI",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Spirit",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Spirit",
["base"] = 13,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["itemTooltipPriority"] = 100,
},
["ATHLETICS"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Athletics",
["category"] = "SKILL",
["id"] = "ATHLETICS",
["base"] = {
["ruleKey"] = "athletics",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["INTIMIDATION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Intimidation",
["category"] = "SKILL",
["id"] = "INTIMIDATION",
["base"] = {
["ruleKey"] = "intimidation",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["MAX_MANA"] = {
["visible"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["id"] = "MAX_MANA",
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["PERFORMANCE"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Performance",
["category"] = "SKILL",
["id"] = "PERFORMANCE",
["base"] = {
["ruleKey"] = "performance",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["STEALTH"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Stealth",
["category"] = "SKILL",
["id"] = "STEALTH",
["base"] = {
["ruleKey"] = "stealth",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["HOLY_RESIST"] = {
["min"] = 0,
["name"] = "Holy",
["category"] = "RESISTANCE",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["id"] = "HOLY_RESIST",
},
["CHA"] = {
["visible"] = 1,
["id"] = "CHA",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Charisma",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Charisma",
["base"] = 11,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["itemTooltipPriority"] = 100,
},
["MELEE_AP"] = {
["itemTooltipPriority"] = 99,
["id"] = "MELEE_AP",
["min"] = 0,
["max"] = {
["ruleKey"] = "max_melee_ap",
},
["name"] = "Attack Power",
["category"] = "SECONDARY",
["base"] = {
["ruleKey"] = "melee_ap",
["default"] = 0,
},
["itemTooltipFormat"] = "$value$ Melee Attack Power",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["itemTooltipColor"] = {
0,
1,
0,
},
},
["SLEIGHT_OF_HAND"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Sleight of Hand",
["category"] = "SKILL",
["id"] = "SLEIGHT_OF_HAND",
["base"] = {
["ruleKey"] = "sleight_of_hand",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["SHADOW_RESIST"] = {
["min"] = 0,
["name"] = "Shadow",
["category"] = "RESISTANCE",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["id"] = "SHADOW_RESIST",
},
["BLOCK"] = {
["itemTooltipPriority"] = 99,
["id"] = "BLOCK",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Block Chance",
["category"] = "SECONDARY",
["base"] = 5,
["itemTooltipFormat"] = "$value$% Block Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\block.png",
["pct"] = 1,
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["id"] = "MAX_HOLY_POWER",
["base"] = 3,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["SPELL_CRIT"] = {
["min"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = {
["ruleKey"] = "spell_crit",
["default"] = 0,
},
["id"] = "SPELL_CRIT",
},
["NATURE_RESIST"] = {
["min"] = 0,
["name"] = "Nature",
["category"] = "RESISTANCE",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["id"] = "NATURE_RESIST",
},
["PERSUASION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Persuasion",
["category"] = "SKILL",
["id"] = "PERSUASION",
["base"] = {
["ruleKey"] = "persuasion",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["HOLY_POWER"] = {
["min"] = 0,
["id"] = "HOLY_POWER",
["name"] = "Holy Power",
["category"] = "RESOURCE",
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["MELEE_HIT"] = {
["itemTooltipPriority"] = 99,
["id"] = "MELEE_HIT",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["base"] = 0,
["itemTooltipFormat"] = "$value$% Melee Hit Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["pct"] = 1,
},
["SPELL_HIT"] = {
["itemTooltipPriority"] = 99,
["id"] = "SPELL_HIT",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["base"] = 0,
["itemTooltipFormat"] = "$value$% Spell Hit Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["pct"] = 1,
},
["PERCEPTION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Perception",
["category"] = "SKILL",
["id"] = "PERCEPTION",
["base"] = {
["ruleKey"] = "perception",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["RANGED_AP"] = {
["min"] = 0,
["name"] = "Ranged Power",
["category"] = "SECONDARY",
["id"] = "RANGED_AP",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = {
["ruleKey"] = "ranged_ap",
["default"] = 0,
},
},
["INT"] = {
["visible"] = 1,
["id"] = "INT",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Intellect",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Intellect",
["base"] = 15,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["itemTooltipPriority"] = 100,
},
["STR"] = {
["visible"] = 1,
["id"] = "STR",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Strength",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Strength",
["base"] = 12,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["itemTooltipPriority"] = 100,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["id"] = "BONUS_ACTION",
["min"] = 0,
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["max"] = 1,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
},
["SURVIVAL"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Survival",
["category"] = "SKILL",
["id"] = "SURVIVAL",
["base"] = {
["ruleKey"] = "survival",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["FIRE_RESIST"] = {
["min"] = 0,
["name"] = "Fire",
["category"] = "RESISTANCE",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["id"] = "FIRE_RESIST",
},
["DECEPTION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Deception",
["category"] = "SKILL",
["id"] = "DECEPTION",
["base"] = {
["ruleKey"] = "deception",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["NATURE"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Nature",
["category"] = "SKILL",
["id"] = "NATURE",
["base"] = {
["ruleKey"] = "nature",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["ARCANA"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Arcana",
["category"] = "SKILL",
["id"] = "ARCANA",
["base"] = {
["ruleKey"] = "arcana",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["RANGED_CRIT"] = {
["min"] = 0,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = {
["ruleKey"] = "ranged_crit",
["default"] = 0,
},
["id"] = "RANGED_CRIT",
},
["PARRY"] = {
["itemTooltipPriority"] = 99,
["id"] = "PARRY",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Parry Chance",
["category"] = "SECONDARY",
["base"] = 5,
["itemTooltipFormat"] = "$value$% Parry Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\parry.png",
["pct"] = 1,
},
["DODGE"] = {
["itemTooltipPriority"] = 99,
["id"] = "DODGE",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Dodge Chance",
["category"] = "SECONDARY",
["base"] = 5,
["itemTooltipFormat"] = "$value$% Dodge Chance",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\dodge.png",
["pct"] = 1,
},
["MANA"] = {
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.\n\nYour maximum mana is $stat.MAX_MANA$.",
["min"] = 0,
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["max"] = {
["ref"] = "MAX_MANA",
},
["base"] = 75,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["HEALTH"] = {
["min"] = 0,
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\n\nYour maximum health is $stat.MAX_HEALTH$.",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["max"] = {
["ref"] = "MAX_HEALTH",
},
},
["HISTORY"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "History",
["category"] = "SKILL",
["id"] = "HISTORY",
["base"] = {
["ruleKey"] = "history",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["MEDICINE"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Medicine",
["category"] = "SKILL",
["id"] = "MEDICINE",
["base"] = {
["ruleKey"] = "medicine",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["ARCANE_RESIST"] = {
["visible"] = "1",
["id"] = "ARCANE_RESIST",
["max"] = "",
["tooltip"] = "",
["itemLevelWeight"] = 0,
["base"] = 0,
["min"] = "0",
["itemTooltipPriority"] = 0,
["name"] = "Arcane",
["category"] = "RESISTANCE",
["recovery"] = "",
["pct"] = "1",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["itemTooltipFormat"] = "",
},
["STA"] = {
["visible"] = 1,
["id"] = "STA",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Stamina",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Stamina",
["base"] = 14,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["itemTooltipPriority"] = 100,
},
["ANIMAL_HANDLING"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Animal Handling",
["category"] = "SKILL",
["id"] = "ANIMAL_HANDLING",
["base"] = {
["ruleKey"] = "animal_handling",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["INVESTIGATION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Investigation",
["category"] = "SKILL",
["id"] = "INVESTIGATION",
["base"] = {
["ruleKey"] = "investigation",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["INSIGHT"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Insight",
["category"] = "SKILL",
["id"] = "INSIGHT",
["base"] = {
["ruleKey"] = "insight",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["FROST_RESIST"] = {
["min"] = 0,
["name"] = "Frost",
["category"] = "RESISTANCE",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["id"] = "FROST_RESIST",
},
["SPELL_AP"] = {
["min"] = 0,
["name"] = "Spell Power",
["category"] = "SECONDARY",
["id"] = "SPELL_AP",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = {
["ruleKey"] = "spell_power",
["default"] = 0,
},
},
["RANGED_HIT"] = {
["min"] = 0,
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["pct"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\ranged.png",
["base"] = 0,
["id"] = "RANGED_HIT",
},
["AGI"] = {
["visible"] = 1,
["id"] = "AGI",
["itemLevelWeight"] = 230,
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Agility",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Agility",
["base"] = 10,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["itemTooltipPriority"] = 100,
},
["ACTION"] = {
["visible"] = 0,
["id"] = "ACTION",
["min"] = 0,
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["max"] = 1,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
},
["RELIGION"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Religion",
["category"] = "SKILL",
["id"] = "RELIGION",
["base"] = {
["ruleKey"] = "religion",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
["ACROBATICS"] = {
["min"] = 0,
["pct"] = 1,
["name"] = "Acrobatics",
["category"] = "SKILL",
["id"] = "ACROBATICS",
["base"] = {
["ruleKey"] = "acrobatics",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["max"] = {
["ruleKey"] = "max_skill",
["default"] = 20,
},
},
},
},
["spells"] = {
},
["auras"] = {
},
["items"] = {
},
["createdAt"] = 1764293249,
["name"] = "5e",
["npcs"] = {
},
["updatedAt"] = 1764300269,
["version"] = 1,
},
},
["activeByChar"] = {
["Ortellus"] = {
"RPE Official 1",
"DefaultDataset",
},
["Ortellus-Argent Dawn"] = {
"DefaultDataset",
},
},
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "RPE Official 1",
},
["_schema"] = 1,
}
