# ReadTheDocs configuration file
version: 2

# Build documentation from the .docs directory
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cd .docs && pip install -r requirements.txt

python:
  install:
    - requirements: .docs/requirements.txt

sphinx:
  configuration: .docs/conf.py

# Formats to build
formats:
  - pdf
  - epub

# Repository settings
repository:
  url: https://github.com/FrontierDev/rpengine
  type: git
