
RPEngineProfilesDB = {
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "Ortellus",
},
["_schema"] = 1,
["profiles"] = {
["Ortellus"] = {
["stats"] = {
["HOLY_POWER"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "HOLY_POWER",
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["base"] = 0,
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
},
["MELEE_CRIT"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MELEE_CRIT",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["ACTION"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "ACTION",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MAX_HEALTH",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["name"] = "Max Health",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["max"] = nil --[[ inf ]],
},
["REACTION"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "REACTION",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["STR"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "STR",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Strength",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["name"] = "Strength",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 12,
["max"] = nil --[[ inf ]],
},
["BONUS_ACTION"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "BONUS_ACTION",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["max"] = 1,
},
["INT"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "INT",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Intellect",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["name"] = "Intellect",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 15,
["max"] = nil --[[ inf ]],
},
["FIRE_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "FIRE_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Fire",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["NATURE_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "NATURE_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Nature",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["MAX_MANA"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MAX_MANA",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Max Mana",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 100,
},
["max"] = nil --[[ inf ]],
},
["SPELL_HIT"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "SPELL_HIT",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Spell Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["STA"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "STA",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Stamina",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["name"] = "Stamina",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 14,
["max"] = nil --[[ inf ]],
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MAX_HOLY_POWER",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["recovery"] = 0,
["pct"] = 0,
["base"] = 3,
["max"] = nil --[[ inf ]],
},
["MANA"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MANA",
["tooltip"] = "Your current mana. Used to power spells and abilities.\\n\\nYour maximum mana is $stat.MAX_MANA$.",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["pct"] = 0,
["base"] = 75,
["max"] = {
["ref"] = "MAX_MANA",
},
},
["HEALTH"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "HEALTH",
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\\n\\nYour maximum health is $stat.MAX_HEALTH$.",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["pct"] = 0,
["base"] = {
["default"] = 0,
["ref"] = "MAX_HEALTH",
},
["max"] = {
["ref"] = "MAX_HEALTH",
},
},
["SPI"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "SPI",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Spirit",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["name"] = "Spirit",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 13,
["max"] = nil --[[ inf ]],
},
["SPELL_AP"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "SPELL_AP",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Spell Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["HOLY_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "HOLY_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Holy",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["CHA"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "CHA",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Charisma",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["name"] = "Charisma",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 11,
["max"] = nil --[[ inf ]],
},
["MELEE_AP"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MELEE_AP",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["FROST_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "FROST_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Frost",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["SHADOW_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "SHADOW_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Shadow",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["PARRY"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipPriority"] = 99,
["id"] = "PARRY",
["itemTooltipFormat"] = "$value$% Parry Chance",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\parry.png",
["name"] = "Parry Chance",
["category"] = "DEFENSE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 5,
["max"] = nil --[[ inf ]],
},
["BLOCK"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipPriority"] = 99,
["id"] = "BLOCK",
["itemTooltipFormat"] = "$value$% Block Chance",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\block.png",
["name"] = "Block Chance",
["category"] = "DEFENSE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 5,
["max"] = nil --[[ inf ]],
},
["DODGE"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipPriority"] = 99,
["id"] = "DODGE",
["itemTooltipFormat"] = "$value$% Dodge Chance",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\dodge.png",
["name"] = "Dodge Chance",
["category"] = "DEFENSE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 5,
["max"] = nil --[[ inf ]],
},
["AGI"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipColor"] = {
1,
1,
1,
},
["itemTooltipPriority"] = 100,
["id"] = "AGI",
["itemLevelWeight"] = 230,
["itemTooltipFormat"] = "$value$ Agility",
["min"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["name"] = "Agility",
["category"] = "PRIMARY",
["recovery"] = 0,
["pct"] = 0,
["base"] = 10,
["max"] = nil --[[ inf ]],
},
["SPELL_CRIT"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "SPELL_CRIT",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Spell Crit. Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["MELEE_HIT"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "MELEE_HIT",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
["ARCANE_RESIST"] = {
["visible"] = 1,
["sourceDataset"] = "DefaultClassic",
["itemTooltipPriority"] = 0,
["id"] = "ARCANE_RESIST",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["name"] = "Arcane",
["category"] = "RESISTANCE",
["recovery"] = 0,
["pct"] = 1,
["base"] = 0,
["max"] = nil --[[ inf ]],
},
},
["spells"] = {
["spell-0dc78974"] = 1,
["spell-e47e1d09"] = 1,
},
["actionBar"] = {
{
["spellId"] = "spell-0dc78974",
["rank"] = 1,
},
{
["spellId"] = "spell-e47e1d09",
["rank"] = 1,
},
},
["items"] = {
},
["createdAt"] = 1764343229,
["name"] = "Ortellus",
["paletteName"] = "Default",
["professions"] = {
["cooking"] = {
["id"] = "Cooking",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["profession1"] = {
["id"] = "",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["fishing"] = {
["id"] = "Fishing",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["profession2"] = {
["id"] = "",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
["firstaid"] = {
["id"] = "First Aid",
["level"] = 0,
["recipes"] = {
},
["spec"] = "",
},
},
["updatedAt"] = 1764544329,
["equipment"] = {
},
},
},
}
RPEngineRulesetDB = {
["rulesets"] = {
["Ruleset 230124"] = {
["rules"] = {
["allowResources"] = "HEALTH, MAX_HEALTH, MANA, MAX_MANA, HOLY_POWER, MAX_HOLY_POWER",
},
["createdAt"] = 1757023284,
["name"] = "Ruleset 230124",
["updatedAt"] = 1757032245,
},
["Ruleset 013052"] = {
["updatedAt"] = 1764544329,
["rules"] = {
["arcana"] = "$stat.SPI$/10",
["nature"] = "$stat.SPI$/10",
["melee_crit"] = "0.05*$stat.AGI$+5",
["perception"] = "$stat.INT$/10",
["sleight_of_hand"] = "$stat.AGI$/10",
["performance"] = "$stat.CHA$/10",
["allow_secondary"] = "{ MELEE_AP, RANGED_AP, SPELL_AP, MELEE_HIT, RANGED_HIT, SPELL_HIT, MELEE_CRIT, RANGED_CRIT, SPELL_CRIT, PARRY, DODGE, BLOCK }",
["hit_system"] = "complex",
["hit_aoe_roll_mode"] = "per_target",
["intimidation"] = "$stat.CHA$/10",
["equipment_slots_left"] = "{ head, neck, shoulder, back, chest, shirt, tabard, wrists  }",
["allow_primary"] = "{ AGI, INT, SPI, STA, CHA, STR }",
["investigation"] = "$stat.INT$/10",
["hit_default_requires"] = "{ DAMAGE, APPLY_AURA_HARMFUL }",
["max_skill"] = "50",
["max_health"] = "10*$stat.STA$",
["equipment_slots_bottom"] = "{ mainhand, offhand, ranged }",
["spell_power"] = "2*$stat.INT$",
["max_mana"] = "10*$stat.INT$",
["stealth"] = "$stat.AGI$/10",
["persuasion"] = "$stat.CHA$/10",
["use_spell_ranks"] = "1",
["equipment_slots_right"] = "{ hands, waist, legs, feet, finger, trinket, ammo, relic }",
["ranged_ap"] = "2*$stat.AGI$",
["spell_crit"] = "0.05*$stat.INT$+5",
["use_spell_ranks_lvl"] = "1",
["deception"] = "$stat.CHA$/10",
["hit_base_threshold"] = "50",
["dataset_require"] = "{ RPE Official 1 }",
["allow_resource"] = "{ HEALTH, MAX_HEALTH, MANA, MAX_MANA, ACTION, BONUS_ACTION, REACTION }",
["show_item_level"] = "1",
["survival"] = "$stat.SPI$/10",
["acrobatics"] = "$stat.AGI$/10",
["hit_roll"] = "1d100",
["religion"] = "$stat.SPI$/10",
["ranged_crit"] = "0.05*$stat.AGI$+5",
["athletics"] = "$stat.STR$/10",
["melee_ap"] = "2*$stat.STR$ + $stat.AGI$",
["medicine"] = "$stat.SPI$/10",
["always_hit"] = "0",
["allow_resistance"] = "{ FIRE_RESIST, FROST_RESIST, NATURE_RESIST, ARCANE_RESIST, SHADOW_RESIST, HOLY_RESIST }",
["mana_regen"] = "$stat.SPI$/4",
["use_level_system"] = "1",
["history"] = "$stat.INT$/10",
["animal_handling"] = "$stat.SPI$/10",
["dataset_exclusive"] = "0",
["npc_stats"] = "{ DODGE, PARRY, BLOCK, FIRE_RESIST, DEFENCE, AC }",
["health_regen"] = "$stat.SPI$/5",
["insight"] = "$stat.SPI$/10",
["max_tick_units"] = "4",
},
["name"] = "Ruleset 013052",
["createdAt"] = 1757032252,
},
},
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "Ruleset 013052",
},
["_schema"] = 1,
}
RPEngineDatasetDB = {
["datasets"] = {
["DefaultClassic"] = {
["notes"] = "Default Classic dataset. Cannot be deleted.",
["guid"] = "DefaultClassic-1764302163-1547796622",
["extra"] = {
["interactions"] = {
},
["stats"] = {
["HOLY_POWER"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["min"] = 0,
["name"] = "Holy Power",
["category"] = "RESOURCE",
["sourceDataset"] = "DefaultClassic",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 0,
["pct"] = 0,
},
["MELEE_CRIT"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
},
["ACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
},
["MAX_HEALTH"] = {
["visible"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "DefaultClassic",
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
},
["REACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
},
["STR"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Strength",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Strength",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["base"] = 12,
["pct"] = 0,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
},
["INT"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Intellect",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Intellect",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["base"] = 15,
["pct"] = 0,
},
["FIRE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Fire",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["SPELL_HIT"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Spell Hit Chance",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["MAX_MANA"] = {
["visible"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "DefaultClassic",
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 100,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["STA"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Stamina",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Stamina",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["base"] = 14,
["pct"] = 0,
},
["ARCANE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Arcane",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["NATURE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Nature",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["MANA"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_MANA",
},
["tooltip"] = "Your current mana. Used to power spells and abilities.\\n\\nYour maximum mana is $stat.MAX_MANA$.",
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 75,
["pct"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_HEALTH",
},
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\\n\\nYour maximum health is $stat.MAX_HEALTH$.",
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = {
["default"] = 0,
["ref"] = "MAX_HEALTH",
},
["pct"] = 0,
},
["FROST_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Frost",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["SPI"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Spirit",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Spirit",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["base"] = 13,
["pct"] = 0,
},
["HOLY_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Holy",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["CHA"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Charisma",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Charisma",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["base"] = 11,
["pct"] = 0,
},
["MELEE_AP"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["base"] = 0,
["pct"] = 0,
},
["SPELL_AP"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Spell Power",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["SHADOW_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Shadow",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["PARRY"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["min"] = 0,
["pct"] = 1,
["name"] = "Parry Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Parry Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\parry.png",
},
["BLOCK"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["min"] = 0,
["pct"] = 1,
["name"] = "Block Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Block Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\block.png",
},
["DODGE"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["min"] = 0,
["pct"] = 1,
["name"] = "Dodge Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Dodge Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\dodge.png",
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "DefaultClassic",
["base"] = 3,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["SPELL_CRIT"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Spell Crit. Chance",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["MELEE_HIT"] = {
["min"] = 0,
["sourceDataset"] = "DefaultClassic",
["name"] = "Hit Chance",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
},
["AGI"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultClassic",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Agility",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Agility",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["base"] = 10,
["pct"] = 0,
},
},
},
["author"] = "RPEngine",
["auras"] = {
},
["items"] = {
},
["createdAt"] = 1764302163,
["name"] = "DefaultClassic",
["npcs"] = {
},
["updatedAt"] = 1764544329,
["spells"] = {
},
["version"] = 1,
},
["RPE Official 1"] = {
["guid"] = "RPEOfficial1-1757872257-125144976",
["extra"] = {
["interactions"] = {
["ixn-7df7f24d"] = {
["id"] = "ixn-7df7f24d",
["options"] = {
{
["args"] = {
["maxStock"] = "inf",
["tags"] = "ink",
},
["action"] = "SHOP",
["label"] = "Shop",
},
{
["args"] = {
["flags"] = "warrior",
["type"] = "SPELLS",
["maxLevel"] = "10",
},
["action"] = "TRAIN",
["label"] = "Train",
},
},
["target"] = "Ink Trader",
},
["ixn-5d9a2abb"] = {
["id"] = "ixn-5d9a2abb",
["options"] = {
{
["label"] = "Salvage",
["action"] = "SALVAGE",
["args"] = {
["maps"] = "37",
},
},
{
["label"] = "Raise Dead",
["action"] = "RAISE",
["args"] = {
},
},
},
["target"] = "type:humanoid",
},
},
["recipes"] = {
["REC-67ece6b0"] = {
["optional"] = {
},
["cost"] = {
["item-4aeda360"] = 1,
},
["id"] = "REC-67ece6b0",
["skill"] = 10,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Dense Triangle Mace",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["quality"] = "rare",
["category"] = "Two-Handed Maces",
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
},
["REC-de3bc56a"] = {
["optional"] = {
},
["id"] = "REC-de3bc56a",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Mace",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["quality"] = "rare",
["category"] = "Two-Handed Maces",
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
},
["REC-a5d82073"] = {
["optional"] = {
},
["id"] = "REC-a5d82073",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Shortsword",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
["category"] = "Two-Handed Maces",
["quality"] = "rare",
},
["REC-c8a9ac6a"] = {
["optional"] = {
},
["cost"] = {
["Copper"] = 134,
["item-abd12b3b"] = 1,
},
["id"] = "REC-c8a9ac6a",
["skill"] = 0,
["outputQty"] = 1,
["outputItemId"] = "item-b7deefa6",
["name"] = "Iron Helmet",
["profession"] = "Blacksmithing",
["tools"] = {
"Hammer",
"Anvil",
},
["reagents"] = {
{
["id"] = "item-abd12b3b",
["qty"] = 1,
},
},
["category"] = "Two-Handed Maces",
["quality"] = "rare",
},
},
["stats"] = {
},
},
["author"] = "Ortellus",
["auras"] = {
},
["items"] = {
["item-759735ed"] = {
["basePriceU"] = 550,
["description"] = "",
["vendorSellable"] = true,
["id"] = "item-759735ed",
["data"] = {
["minDamage"] = "6",
["slot"] = "MAIN_HAND",
["weaponType"] = "mace",
["maxDamage"] = "12",
},
["itemLevel"] = 0,
["tags"] = {
"test",
},
["priceOverrideC"] = 0,
["name"] = "Test Item",
["category"] = "EQUIPMENT",
["maxStack"] = 1,
["stackable"] = false,
["icon"] = 132176,
["rarity"] = "common",
},
},
["createdAt"] = 1757872257,
["name"] = "RPE Official 1",
["npcs"] = {
["NPC-8efa77ab"] = {
["stats"] = {
["DODGE"] = 5,
["FIRE_RESIST"] = 0,
["BLOCK"] = 7,
["PARRY"] = 11,
["DEFENCE"] = 8,
["AC"] = 12,
},
["cam"] = 0.5,
["id"] = "NPC-8efa77ab",
["spells"] = {
"spell-0dc78974",
"spell-e47e1d09",
},
["hp"] = {
["base"] = 70,
["perPlayer"] = 5,
},
["fileDataId"] = 1100490,
["unitType"] = "Demon",
["name"] = "Kharduum Legionnaire",
["z"] = -0.16,
["team"] = 1,
["unitSize"] = "Medium",
["displayId"] = 18342,
["rot"] = 0.5,
},
},
["updatedAt"] = 1764544329,
["spells"] = {
["spell-0dc78974"] = {
["unlockLevel"] = 1,
["alwaysKnown"] = true,
["description"] = "Deals $[1].amount$ Physical damage.",
["npcOnly"] = false,
["id"] = "spell-0dc78974",
["icon"] = 132282,
["data"] = {
},
["maxRanks"] = 6,
["costs"] = {
{
["resource"] = "action",
["amount"] = "1",
["when"] = "onStart",
["perRank"] = "0",
["refundOnInterrupt"] = false,
},
},
["targeter"] = {
["default"] = "PRECAST",
},
["groups"] = {
{
["requirements"] = {
},
["logic"] = "ALL",
["actions"] = {
{
["hitModifier"] = "$stat.MELEE_HIT$",
["hitThreshold"] = {
"$stat.PARRY$",
"$stat.DODGE$",
"$stat.BLOCK$",
"$stat.DEFENCE$",
"$stat.AC$",
},
["key"] = "DAMAGE",
["args"] = {
["threat"] = "",
["perRank"] = "4",
["school"] = "Physical",
["amount"] = "2d8",
["targets"] = {
["targeter"] = "PRECAST",
["maxTargets"] = 1,
["flags"] = "E",
},
["requiresHit"] = true,
},
},
},
["phase"] = "onResolve",
},
},
["name"] = "Heroic Strike",
["rankInterval"] = 6,
["cast"] = {
["tickIntervalTurns"] = 1,
["type"] = "CAST_TURNS",
["concentration"] = false,
["turns"] = 1,
["moveAllowed"] = false,
},
["cooldown"] = {
["starts"] = "onResolve",
},
["tags"] = {
"warrior",
"arms",
},
},
["spell-e47e1d09"] = {
["unlockLevel"] = 1,
["alwaysKnown"] = false,
["description"] = "Heals the target for $[1].amount$ hitpoints.",
["npcOnly"] = false,
["id"] = "spell-e47e1d09",
["icon"] = 135913,
["data"] = {
},
["maxRanks"] = 9,
["costs"] = {
{
["resource"] = "mana",
["amount"] = "5",
["when"] = "onResolve",
["perRank"] = "1",
["refundOnInterrupt"] = false,
},
},
["targeter"] = {
["default"] = "PRECAST",
},
["groups"] = {
{
["requirements"] = {
},
["logic"] = "ALL",
["actions"] = {
{
["key"] = "HEAL",
["args"] = {
["perRank"] = 1,
["targets"] = {
["targeter"] = "PRECAST",
["maxTargets"] = 1,
},
["amount"] = "1d4",
},
},
},
["phase"] = "onResolve",
},
},
["name"] = "Greater Heal",
["rankInterval"] = 7,
["cast"] = {
["tickIntervalTurns"] = 1,
["type"] = "CAST_TURNS",
["concentration"] = false,
["turns"] = 1,
["moveAllowed"] = false,
},
["cooldown"] = {
["starts"] = "onResolve",
},
["tags"] = {
"warrior",
"arms",
},
},
},
["version"] = 1,
},
["Default5e"] = {
["notes"] = "Default 5e (D&D Fifth Edition) dataset. Cannot be deleted.",
["guid"] = "Default5e-1764302163-1078459643",
["extra"] = {
["interactions"] = {
},
["stats"] = {
["AC"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Armor Class",
["category"] = "DEFENSE",
["itemTooltipFormat"] = "$value$ AC",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\healed_last.png",
["base"] = 10,
["pct"] = 0,
},
["NATURE"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Nature",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["MAX_HEALTH"] = {
["visible"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "Default5e",
["base"] = {
["ruleKey"] = "max_health",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
},
["REACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "Default5e",
["name"] = "Reactions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "reaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\reaction.png",
},
["ATHLETICS"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Athletics",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["INTIMIDATION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Intimidation",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["MAX_MANA"] = {
["visible"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "Default5e",
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 100,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["PERFORMANCE"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Performance",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["STEALTH"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Stealth",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["CHA"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Charisma",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Charisma",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\cha.png",
["base"] = 10,
["pct"] = 0,
},
["SLEIGHT_OF_HAND"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Sleight of Hand",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["INSIGHT"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Insight",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["MAX_HOLY_POWER"] = {
["visible"] = 0,
["name"] = "Max Holy Power",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "Default5e",
["base"] = 3,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["HOLY_POWER"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_HOLY_POWER",
},
["tooltip"] = "Divine power used to perform powerful Paladin-specific spells.",
["min"] = 0,
["name"] = "Holy Power",
["category"] = "RESOURCE",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 0,
["pct"] = 0,
},
["ACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "Default5e",
["name"] = "Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "action_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
},
["STR"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Strength",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Strength",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["base"] = 10,
["pct"] = 0,
},
["BONUS_ACTION"] = {
["visible"] = 0,
["max"] = 1,
["min"] = 0,
["sourceDataset"] = "Default5e",
["name"] = "Bonus Actions",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "bonusaction_regen",
["default"] = 1,
},
["pct"] = 0,
["base"] = 1,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\bonus_action.png",
},
["INT"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Intelligence",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Intelligence",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["base"] = 10,
["pct"] = 0,
},
["HISTORY"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "History",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["DECEPTION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Deception",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["WIS"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Wisdom",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Wisdom",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["base"] = 10,
["pct"] = 0,
},
["MANA"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_MANA",
},
["tooltip"] = "Your current mana. Used to power spells and abilities.\\n\\nYour maximum mana is $stat.MAX_MANA$.",
["min"] = 0,
["sourceDataset"] = "Default5e",
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = 75,
["pct"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_HEALTH",
},
["tooltip"] = "Your current hitpoints. If this reaches 0, you are knocked out.\\n\\nYour maximum health is $stat.MAX_HEALTH$.",
["min"] = 0,
["sourceDataset"] = "Default5e",
["name"] = "Hitpoints",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = {
["default"] = 0,
["ref"] = "MAX_HEALTH",
},
["pct"] = 0,
},
["MEDICINE"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Medicine",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["DEX"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Dexterity",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Dexterity",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["base"] = 10,
["pct"] = 0,
},
["INVESTIGATION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Investigation",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["SURVIVAL"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Survival",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["CON"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "Default5e",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Constitution",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Constitution",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["base"] = 10,
["pct"] = 0,
},
["PERSUASION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Persuasion",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["PERCEPTION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Perception",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["ARCANA"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Arcana",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["ANIMAL_HANDLING"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Animal Handling",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["RELIGION"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Religion",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
["ACROBATICS"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["min"] = nil --[[ inf ]],
["name"] = "Acrobatics",
["category"] = "SKILL",
["sourceDataset"] = "Default5e",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = 0,
["pct"] = 0,
},
},
},
["author"] = "RPEngine",
["auras"] = {
},
["items"] = {
},
["createdAt"] = 1764302163,
["name"] = "Default5e",
["npcs"] = {
},
["updatedAt"] = 1764344118,
["spells"] = {
},
["version"] = 1,
},
["DefaultWarcraft"] = {
["notes"] = "Default Warcraft dataset. Cannot be deleted.",
["guid"] = "DefaultWarcraft-1764302163-1423682244",
["extra"] = {
["interactions"] = {
},
["stats"] = {
["DODGE"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["pct"] = 1,
["name"] = "Dodge Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Dodge Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\dodge.png",
},
["MELEE_CRIT"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["pct"] = 1,
["name"] = "Crit. Chance",
["category"] = "SECONDARY",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Melee Crit. Chance",
["base"] = {
["ruleKey"] = "melee_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
},
["MAX_HEALTH"] = {
["visible"] = 0,
["max"] = nil --[[ inf ]],
["min"] = 0,
["name"] = "Max Health",
["category"] = "RESOURCE",
["sourceDataset"] = "DefaultWarcraft",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = {
["ruleKey"] = "max_health",
["default"] = 100,
},
["pct"] = 0,
},
["STR"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Strength",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Strength",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\str.png",
["base"] = 8,
["pct"] = 0,
},
["SPI"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Spirit",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Spirit",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spi.png",
["base"] = 6,
["pct"] = 0,
},
["INT"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Intellect",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Intellect",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\int.png",
["base"] = 9,
["pct"] = 0,
},
["FIRE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Fire",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["MAX_MANA"] = {
["visible"] = 0,
["name"] = "Max Mana",
["category"] = "RESOURCE",
["pct"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["base"] = {
["ruleKey"] = "max_mana",
["default"] = 100,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
},
["ENERGY"] = {
["visible"] = 1,
["max"] = 100,
["tooltip"] = "Your current energy. Used to perform rogue abilities.",
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Energy",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "energy_regen",
["default"] = 10,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["base"] = 100,
["pct"] = 0,
},
["MANA"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_MANA",
},
["tooltip"] = "Your current mana. Used to power spells.\\n\\nYour maximum mana is $stat.MAX_MANA$.",
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Mana",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "mana_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\mana.png",
["base"] = {
["default"] = 0,
["ref"] = "MAX_MANA",
},
["pct"] = 0,
},
["HEALTH"] = {
["visible"] = 1,
["max"] = {
["ref"] = "MAX_HEALTH",
},
["tooltip"] = "Your current health. If this reaches 0, you are dead.\\n\\nYour maximum health is $stat.MAX_HEALTH$.",
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Health",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "health_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\health.png",
["base"] = {
["default"] = 1,
["ref"] = "MAX_HEALTH",
},
["pct"] = 0,
},
["BLOCK"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["pct"] = 1,
["name"] = "Block Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Block Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\block.png",
},
["PARRY"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["pct"] = 1,
["name"] = "Parry Chance",
["category"] = "DEFENSE",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$% Parry Chance",
["base"] = 5,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\parry.png",
},
["HOLY_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Holy",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["ARMOR"] = {
["itemTooltipPriority"] = 99,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["itemTooltipColor"] = {
0,
1,
0,
},
["name"] = "Armor",
["category"] = "DEFENSE",
["itemTooltipFormat"] = "$value$ Armor",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\block.png",
["base"] = 0,
["pct"] = 0,
},
["MELEE_AP"] = {
["itemTooltipPriority"] = 99,
["max"] = {
["ruleKey"] = "max_melee_ap",
},
["sourceDataset"] = "DefaultWarcraft",
["min"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\melee.png",
["name"] = "Attack Power",
["category"] = "SECONDARY",
["itemTooltipColor"] = {
0,
1,
0,
},
["itemTooltipFormat"] = "$value$ Melee Attack Power",
["base"] = {
["ruleKey"] = "melee_ap",
["default"] = 0,
},
["pct"] = 0,
},
["ARCANE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Arcane",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["SHADOW_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Shadow",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["FROST_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Frost",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["SPELL_AP"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Spell Power",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
["base"] = {
["ruleKey"] = "spell_power",
["default"] = 0,
},
["pct"] = 0,
},
["STA"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Stamina",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Stamina",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\sta.png",
["base"] = 8,
["pct"] = 0,
},
["AGI"] = {
["visible"] = 1,
["max"] = nil --[[ inf ]],
["sourceDataset"] = "DefaultWarcraft",
["itemLevelWeight"] = 230,
["itemTooltipPriority"] = 100,
["min"] = nil --[[ inf ]],
["itemTooltipColor"] = {
1,
1,
1,
},
["name"] = "Agility",
["category"] = "PRIMARY",
["itemTooltipFormat"] = "$value$ Agility",
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\agi.png",
["base"] = 7,
["pct"] = 0,
},
["SPELL_CRIT"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Spell Crit. Chance",
["category"] = "SECONDARY",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = {
["ruleKey"] = "spell_crit",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["NATURE_RESIST"] = {
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Nature",
["category"] = "RESISTANCE",
["max"] = nil --[[ inf ]],
["pct"] = 1,
["base"] = 0,
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\spell.png",
},
["RAGE"] = {
["visible"] = 1,
["max"] = 100,
["tooltip"] = "Your current rage. Used to perform powerful warrior abilities.",
["min"] = 0,
["sourceDataset"] = "DefaultWarcraft",
["name"] = "Rage",
["category"] = "RESOURCE",
["recovery"] = {
["ruleKey"] = "rage_regen",
["default"] = 0,
},
["icon"] = "Interface\\Addons\\RPEngine\\UI\\Textures\\action.png",
["base"] = 0,
["pct"] = 0,
},
},
},
["author"] = "RPEngine",
["auras"] = {
},
["items"] = {
},
["createdAt"] = 1764302163,
["name"] = "DefaultWarcraft",
["npcs"] = {
},
["updatedAt"] = 1764506169,
["version"] = 1,
["spells"] = {
},
},
},
["activeByChar"] = {
["Ortellus"] = {
"RPE Official 1",
},
["Ortellus-Argent Dawn"] = {
"RPE Official 1",
"DefaultClassic",
},
},
["currentByChar"] = {
["Ortellus-Argent Dawn"] = "RPE Official 1",
},
["_schema"] = 1,
}
